export const CATEGORIES = {
  expense: [
    { id: 'food', label: { en: 'Food & Dining', mm: 'အစားအသောက်' }, icon: 'Utensils' },
    { id: 'transport', label: { en: 'Transport', mm: 'လမ်းစရိတ်' }, icon: 'Bus' },
    { id: 'shopping', label: { en: 'Shopping', mm: 'ဈေးဝယ်' }, icon: 'ShoppingBag' },
    { id: 'bills', label: { en: 'Bills & Utilities', mm: 'မီတာ/ရေဖိုး' }, icon: 'Zap' },
    { id: 'health', label: { en: 'Health', mm: 'ကျန်းမာရေး' }, icon: 'HeartPulse' },
    { id: 'others', label: { en: 'Others', mm: 'အခြား' }, icon: 'MoreHorizontal' },
  ],
  income: [
    { id: 'salary', label: { en: 'Salary', mm: 'လစာ' }, icon: 'Banknote' },
    { id: 'business', label: { en: 'Business', mm: 'လုပ်ငန်း' }, icon: 'Briefcase' },
    { id: 'gift', label: { en: 'Gift', mm: 'လက်ဆောင်' }, icon: 'Gift' },
    { id: 'others', label: { en: 'Others', mm: 'အခြား' }, icon: 'MoreHorizontal' },
  ]
};

export const TRANSLATIONS = {
  en: {
    greetingMorning: "Good Morning",
    greetingAfternoon: "Good Afternoon",
    greetingEvening: "Good Evening",
    totalBalance: "Total Balance",
    income: "Income",
    expense: "Expense",
    recentTransactions: "Recent Transactions",
    seeAll: "See All",
    addTransaction: "Add Transaction",
    dashboard: "Dashboard",
    list: "Transactions",
    settings: "Settings",
    language: "Language",
    darkMode: "Dark Mode",
    signOut: "Sign Out",
    loginGoogle: "Sign in with Google",
    processing: "Processing AI...",
    listening: "Listening...",
    save: "Save",
    cancel: "Cancel",
    description: "Description",
    amount: "Amount",
    date: "Date",
    note: "Note (Optional)",
    budgetHealth: "Budget Health",
    exportCsv: "Export CSV",
    confirmDelete: "Delete this transaction?",
    all: "All"
  },
  mm: {
    greetingMorning: "မင်္ဂလာနံနက်ခင်းပါ",
    greetingAfternoon: "မင်္ဂလာနေ့လည်ခင်းပါ",
    greetingEvening: "မင်္ဂလာညချမ်းပါ",
    totalBalance: "လက်ကျန်ငွေ",
    income: "ဝင်ငွေ",
    expense: "ထွက်ငွေ",
    recentTransactions: "လတ်တလော စာရင်းများ",
    seeAll: "အားလုံးကြည့်မည်",
    addTransaction: "စာရင်းသစ်ထည့်မည်",
    dashboard: "ပင်မ",
    list: "စာရင်းများ",
    settings: "ဆက်တင်",
    language: "ဘာသာစကား",
    darkMode: "အမှောင်မုဒ်",
    signOut: "အကောင့်ထွက်မည်",
    loginGoogle: "Google ဖြင့် ဝင်မည်",
    processing: "AI လုပ်ဆောင်နေပါသည်...",
    listening: "နားထောင်နေသည်...",
    save: "သိမ်းမည်",
    cancel: "မလုပ်တော့ပါ",
    description: "အကြောင်းအရာ",
    amount: "ပမာဏ",
    date: "ရက်စွဲ",
    note: "မှတ်ချက် (ရှိလျှင်)",
    budgetHealth: "ဘတ်ဂျက် အခြေအနေ",
    exportCsv: "CSV ထုတ်မည်",
    confirmDelete: "ဖျက်မည်မှာ သေချာလား?",
    all: "အားလုံး"
  }
};